# Generated by Django 4.2 on 2023-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("F_name", models.CharField(blank=True, max_length=255, null=True)),
                ("S_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                ("job_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "years_of_experience",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "education_history",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "acquired_skills",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "other_skills",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="employer_dashboard",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("post_job_opening", models.CharField(max_length=3000)),
                ("view_job_applicants", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="job_applicants",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("view_resumes_sent", models.CharField(max_length=100000)),
                ("rank_resumes_sent", models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name="jobseeker_dashboard",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("upload_resume", models.CharField(max_length=3000)),
                ("upload_skills", models.CharField(max_length=3000)),
                ("view_qualified_jobs", models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "username",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RequirementsInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("F_name", models.CharField(blank=True, max_length=255, null=True)),
                ("S_name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone_number", models.CharField(max_length=255)),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                ("job_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "years_of_experience",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "education_history",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "acquired_skills",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "other_skills",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillsInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("employer", "Employer"), ("jobseeker", "Jobseeker")],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
