# Generated by Django 4.2 on 2023-04-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requirementsinput",
            old_name="acquired_skills",
            new_name="skills",
        ),
        migrations.RemoveField(
            model_name="requirementsinput",
            name="F_name",
        ),
        migrations.RemoveField(
            model_name="requirementsinput",
            name="S_name",
        ),
        migrations.RemoveField(
            model_name="requirementsinput",
            name="education_history",
        ),
        migrations.RemoveField(
            model_name="requirementsinput",
            name="email_address",
        ),
        migrations.RemoveField(
            model_name="requirementsinput",
            name="other_skills",
        ),
        migrations.RemoveField(
            model_name="requirementsinput",
            name="phone_number",
        ),
    ]
