# Generated by Django 4.2 on 2023-04-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_acquired_skills_requirementsinput_skills_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="details",
            name="job_name",
        ),
    ]
