# Generated by Django 4.2 on 2023-04-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_details_job_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='acquired_skills',
            new_name='Certifications',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='F_name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='S_name',
            new_name='Second_name',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='education_history',
            new_name='education',
        ),
        migrations.RemoveField(
            model_name='details',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='details',
            name='Personal_intrests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='Projects',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='Work_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='technical_skills_required',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
