# Generated by Django 4.2 on 2023-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_education_details_education_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='First_name',
            new_name='F_name',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='Second_name',
            new_name='S_name',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='Certifications',
            new_name='acquired_skills',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Personal_intrests',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Projects',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Work_experience',
        ),
        migrations.RemoveField(
            model_name='details',
            name='technical_skills_required',
        ),
        migrations.AddField(
            model_name='details',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
