# Generated by Django 4.2 on 2023-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_first_name_details_f_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementsinput',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
